### ISSUE TITLE
Tag / source for 0.2.2.0 nuget release of pjsip4net?

### ISSUE THREAD

**Issue by rggammon** [siniypin/pjsip4net#100]
I am trying to build pjsip4net from source, corresponding to what is published to nuget. I am using 0.2.2.0 (unlisted release)? I am unable to match this to git - eg: in Git, Castle.Windsor.3.3.0 is used, whereas https://www.nuget.org/packages/pjsip4net/0.2.2.0 shows a dependency on Castle.Windsor.2.5.1.

I was just wondering if the source for 0.2.2.0 is on github?

Thank you for creating this library! :)

**Comment by rggammon** [comment]
Similar question for pjsip version and what the binaries were built against - I think the binaries are from pjsip 1.4? I am having trouble getting the source to line up with interop definitions. For example, for struct pjsua_config, the "cb" member is in different locations. The interop assembly puts it at the end of the struct, but pjproject has it between cred_info and user_agent. 

https://github.com/pjsip/pjproject/blob/50af78138e12fe50eb86778c6ba6df15e2593d4b/pjsip/include/pjsua-lib/pjsua.h#L1007

https://github.com/siniypin/pjsip4net/blob/e09a511a5d4c97d5884025424b93b16a035b1973/pjsip.Interop/Interop.cs#L13622

**Comment by siniypin** [comment]
Hi,

this should be a correct version https://www.nuget.org/packages/pjsip4net/0.2.0.28. Perhaps, I should update a NuGet package, as there were a few pull requests merged down since that version was published.  

Indeed the version of pjsip I used to compile the dll files was 1.4. I don't have an easy access to that code to lookup the exact commit anymore. However, the entire interop code was auto generated by a tool called https://github.com/jaredpar/pinvoke-interop-assistant. I can bet it respects the order of fields in structures.   

> Thank you for creating this library! :)

you are welcome!

**Comment by rggammon** [comment]
Thanks for the information - in the version of 1.4 I checked out of github, reordering cb was the only thing that I had to do to to get a local build working.
