### ISSUE TITLE
pjsip4net.Core.PjsipErrorException: "PJSIP error code =  15:04:09.963  pjsua_media.c  Media stack initialization has returned error: Found no audio devices (PJMEDIA_EAUD_NODEV) [status=420005]  in InitPjsua

### ISSUE THREAD

**Issue by ImWolfy** [siniypin/pjsip4net#106]
At first I'm sorry for my English, this is not my native language.
My application can be run on the server without audio devices. It only should receive a caller number and should not answer (another application on the client PCs answers calls). But when I start the application, I get an error from the title. How can I fix this problem?

**Comment by siniypin** [comment]
Hi ImWolfy,

the reason it fails is pjsip4net running on an old pjsip version (1.4) and the aforementioned problem was fixed in 1.5 (see https://trac.pjsip.org/repos/ticket/968).

As a quick and dirty fix you can try the follwing: compile a pjsua.dll using a 1.5 tag and swap it with the one that comes with pjsip4net, hoping that it won't notice the difference.

Cheers.

**Comment by siniypin** [comment]
Hey, did you by any chance try the fix I had suggested? It would be nice if you'd share your 1.5 lib .dll file with the rest of us.
