### ISSUE TITLE
AccessViolationException - Register Users

### ISSUE THREAD

**Issue by xcyphercodex** [siniypin/pjsip4net#34]
Hi,
I would like to register some users, but after the 7. user i get an AccessViolationException.

StackTrace:
pjsip.Interop.PJSUA_DLL.Accounts.pjsua_acc_add(pjsua_acc_config acc_cfg, Int32 is_default, Int32& p_acc_id)

pjsip.Interop.ApiProviders.AccountApiProvider_1_4.AddAccountAndGetId(AccountConfig accCfg, Boolean isDefault) in ...\pjsip.Interop\ApiProviders\AccountApiProvider_1_4.cs:Line 49.

pjsip4net.Accounts.DefaultAccountManager.RegisterAccount(Account account, Boolean default) in ...\pjsip4net\Accounts\DefaultAccountManager.cs:Line 96.

at AccountApiProvider_1_4.cs:Line 49 stopped the Debugger

Thanks

**Comment by xcyphercodex** [comment]
I use a pjsip4net version from 26/06/2015, because I can't start the current version. (log4net conf errors)

**Comment by siniypin** [comment]
Hi, thanks for noting, I'll check this up and will write back to you.

Cheers

**Comment by siniypin** [comment]
Hi, can you please update to the latest version? I have fixed an error with logger.

As for the AV error - looks like you've hit the threshold. The native pjsua.dll that pjsip4net uses was built with constant PJSUA_MAX_ACC = 8;

How many accounts do you need to register? Would running several user agents be an option for you?

Cheers,
Boris

**Comment by xcyphercodex** [comment]
Thanks for your answer.
Can I change the parameters?
Or do I have to compile my own pjsua.dll version?
I want one user agent with more than thousand accounts / calls.
Several user agents need too much power (RAM / CPU)?

**Comment by siniypin** [comment]
Hi,

I'm afraid CPU and RAM wouldn't be your biggest problems. But the network throughput will. 
In order to change the maximum allowed accounts you'll have to build your own pjsua.dll version. There is some information in issue #15. Please note, that currently used pjsua version number is 1.4, it is the version interop code was generated against. I can't guarantee that pjsip4net will work with your dll, if you build it with the newer version.

I'm going to close this issue, if have other concerns, please open another issue.

Cheers,
Boris

**Comment by xcyphercodex** [comment]
Thanks,
I think network throughput is not my problem. :)
Can you share your current pjsip project ?
