### ISSUE TITLE
Vonage voip configuration

### ISSUE THREAD

**Issue by maqeelqureshi** [siniypin/pjsip4net#38]
I have vonage voip softphone account that works fine with x-lite. How can I use it with .Net wrapper. 

Vonage provides me following parameters,
userName
displayName
authenticationId
registerPassword
domainHost

While this sdk reads following values from config file.
accountId
registrarUri
userName
password
realm

**Comment by siniypin** [comment]
Basically, in order to connect to any SIP registrar one needs an extension (likely a userName/userName), password (likely a registerPassword/password) and a registrar uri (likely a domainHost/registrarUri). Realm is most often equals domainHost and an accountId is just a full SIP uri, e.g.: sip:user:password@sip.org. Here is an example of possible config: https://gist.github.com/siniypin/7860029 Try it out for yourself  and let me know if that works.

Cheers.
