### ISSUE TITLE
Problem with incoming calls

### ISSUE THREAD

**Issue by rootuser** [siniypin/pjsip4net#8]
Hello,

I have created a small application in visual basic that registers a sip account and then waits for incoming calls. 

You may download the full example code using the following link:
https://www.dropbox.com/s/yxlkw5v2ot7qqhs/incoming_call.zip

For testing I used my personal sipgate account (sipgate team), so maybe with other providers your experience will be different.

I got the following issue:
When registered successfully, incoming calls are indicated in the log window. In the example, the event writes the contents of the  pjsip4net.Core.Utils.EventArgs.Data.RemoteInfo variable into the log window. But instead of the expected caller number I only get strange characters (see image below)

![incoming](https://f.cloud.github.com/assets/2338642/785140/02aa7080-ea75-11e2-9d4c-b1e71c90efcc.png)

I have compiled the pjsip4net dll files both on Visual Studio 2010 and 2012 with the same results.

Any help is welcome!

Thank you very much, 
regards, Tom

**Comment by lcop200685** [comment]
Hi

I want to know if this issue was resolve, I have a similar problem, the context is:

- I have n Accounts  active in my sip client in c#, when Arrive new call,  I need to see who is calling and who is called , but the callback of incoming call give me this symbols
![image](https://cloud.githubusercontent.com/assets/3520983/6643527/de7d99f8-c97a-11e4-84fd-7e08a9ceddd7.png)

Can you help me? thanks

**Comment by siniypin** [comment]
I'm currently working on it.
